"""add car brands and models

Revision ID: 0952d204e0dd
Revises: 6b0263555a83
Create Date: 2026-05-12 15:48:32.371817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0952d204e0dd'
down_revision: Union[str, None] = 'fe47b3289148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('car_brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_car_brands_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_brands_slug'), ['slug'], unique=True)

    op.create_table('car_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['car_brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('car_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_car_models_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_models_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_car_models_slug'))
        batch_op.drop_index(batch_op.f('ix_car_models_id'))

    op.drop_table('car_models')
    with op.batch_alter_table('car_brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_car_brands_slug'))
        batch_op.drop_index(batch_op.f('ix_car_brands_id'))

    op.drop_table('car_brands')
    # ### end Alembic commands ###
