"""add_bookings_table

Revision ID: 3be8df73c7ba
Revises: 3e6ef921a860
Create Date: 2026-04-24 22:10:33.394720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3be8df73c7ba'
down_revision: Union[str, None] = '3e6ef921a860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
